name: storage_view
description: Flutter inspector tool for any database, storage and shared_preferences
version: 0.1.0-dev.3
homepage: https://github.com/Frezyx/storage_view

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  talker: ^4.1.3
  talker_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
