name: storage_view
description: Flutter inspector tool for any database, storage and shared_preferences
version: 0.1.0-dev.2
homepage: https://github.com/Frezyx/storage_view

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  talker: ^3.1.4
  talker_flutter: ^3.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
