name: shared_preferences_storage_view_driver
description: Shared preferences driver for storage_view. Flutter inspector tool for any database, storage
version: 0.1.0-dev.4
homepage: https://github.com/Frezyx/storage_view

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  storage_view: ^0.1.0-dev.4
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
