name: flutter_secure_storage_view_driver
description: Flutter secure storage driver for storage_view. Flutter inspector tool for any database, storage
version: 0.1.0-dev.2
homepage: https://github.com/Frezyx/storage_view

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  storage_view: 0.1.0-dev.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
